### ISSUE TITLE
Using TCK with JUnit4?

### ISSUE THREAD

**Issue by spodkowinski** [reactive-streams/reactive-streams#216]
I'd like to integrate the TCK with a set of existing JUnit tests we keep in one of our libraries. So far this turned out to be rather painful and a bit of a hack. Is there any preferred way to use the TCK with a JUnit test runner? I'm a bit surprissed this turned out to be rather difficult although the TCK only seems to make use of the most basic annotations without anything testng specific.

**Comment by viktorklang** [comment]
Hi @spodkowinski,

We initially started the TCK on JUnit ( @sirthias can most definitely share some war stories from that attempt) so we had to resort to TestNG.

There seems to be multiple ways to run both TestNG and JUnit tests in the same project, but it depends on what build tool you use, `sbt` with `ScalaTest` handles it well, and there seems to be ways to do it for `Maven` etc here: https://stackoverflow.com/questions/1232853/how-to-execute-junit-and-testng-tests-in-same-project-using-maven-surefire-plugi

On that note, it would indeed be great to have an easily accessible step-by-step guide how to integrate the TCK with the common build tools.

**Comment by spodkowinski** [comment]
Talking about war stories.. I was first trying to make the test work using the TestNG Eclipse plugin. I can start all JUnit tests just fine in Eclipse. The TestNG plugin however would always fail due to a NoSuchMethodError. Looks like my project uses a different snakeyaml version than the testng plugin was compiled against (what happened to osgi?). 

So I tried one of the suggested [maven solutions](http://stackoverflow.com/a/19928639/1662877) for this issue. Without much success either. When I just enable the testng runner its executing just fine. When I enable the junit counterpart as well, maven will just exit after complaining about about invalid parameters. See [gist](https://gist.github.com/spodkowinski/8234f083ae6d5d49a3f5) for details.

**Comment by viktorklang** [comment]
@spodkowinski Should work according to this: https://solidsoft.wordpress.com/2013/03/12/mixing-testng-and-junit-tests-in-one-maven-module-2013-edition/ and http://confluence.highsource.org/display/~lexi/How+to+run+both+JUnit+and+TestNG+with+maven-surefire-plugin
Could you try that?

**Comment by smaldini** [comment]
Just works oob with Gradle, we use that in Reactor, we even mix junit with testng under the same test class.

**Comment by spodkowinski** [comment]
@viktorklang thaks, I've tried both links and this [1][2] version seems to do the trick. However, its only working with surefire 2.15, which is a quite dated version of the plugin. The version described on the confluence page will also execute both types of tests, but will not execute both of them in case either a junit or testng test fails.

[1] https://solidsoft.wordpress.com/2013/03/12/mixing-testng-and-junit-tests-in-one-maven-module-2013-edition/
[2] https://github.com/szpak/code-examples-and-poc/blob/master/testng-and-junit-maven-poc/pom.xml

**Comment by viktorklang** [comment]
@spodkowinski Great that you managed to get it working, even though there are definitely improvements one would want to have.

**Comment by viktorklang** [comment]
Can we consider this closed?

**Comment by lukaseder** [comment]
In case it helps, this seems to work for me: https://gist.github.com/lukaseder/667c860bd18340a8b04e2530cd1001b5
